### ISSUE TITLE
Don't have proper scope for authenticating tokenizers.

### ISSUE THREAD

**Issue by 7db9a** [turbo-src/extension#39]
As part of the tokenization process,  tokenizers must re-authenticate with requested scope. Should automatically request `public_repo` scope when they click "tokenize". If possible, set it so it doesn't default to expire. Believe you can set it so it doesn't. We're not interested in `repo`, which includes private repo access.

UPDATE: think we'll have to deal with expiring tokens. They expire every 8 hours. To my understanding, you make a request with the old token and you get a new one. This can be done server-side so the Turbosrc services can take care of this.

https://docs.github.com/en/developers/apps/building-github-apps/refreshing-user-to-server-access-tokens

**Comment by JeffreyLWood** [comment]
This is a temporary solution to get the additional scopes:
https://github.com/turbo-src/extension/tree/scope

 It just requests scopes for public_repo on login. Ideally we want to request these additional scopes when a user wants to create a repo. 

Until we think of the best way to implement that this will do for now.

Simply calling the Oauth link to additional scopes when a user clicks create repo did not really work, or was at best a confusing user experience (how does it know to do it once and then not again?). 

So in case you need to just play around with the fact that users have public_repo scopes enabled use the branch "scope" as the token will have the correct scopes until we figure out the best way to implement the request additional scopes on create repo feature. I will continue to work on implementing the functionality we actually want.

**Comment by JeffreyLWood** [comment]
On the branch called "scope" there is functionality to check the scopes of a user before they tokenize. If their scopes are only user:email, a message is rendered asking them to update their scopes. Clicking the button authenticates them through Github with the public_repo scope. When the user visits the tokenize page again, the warning message is not rendered and they can click the button to tokenize the current repository.

An additional npm package was used to achieve this: Octokit. The core functionality is in Onboard2.js and is copied here:

```
useEffect(()=>{
const checkScope = async() => {
if(!repo || !owner){
return
}
const octokit = new Octokit({ auth: user.token });
const res = await octokit.request(`GET /repos/${owner}/${repo}`)

Promise.resolve(res).then((object) => {
if(object.headers['x-oauth-scopes'].split(',').includes('public_repo')) {
setVerified(true)
} else {
setVerified(false)
}})}

checkScope()
}, [owner,repo])
```

There is likely room for optimization here. For example, perhaps we can check the scopes of a user's tokens without Octokit. However, in the likely scenario we not only want to verify whether or not a user's token has the public_repo scope but whether or not they actually have read/write access to the repository they want to tokenize, I believe we could achieve that too here. Checking if a user has the public_repo scope is only part of the process, checking if they are trying to tokenize a repository they do not have access to is also relevant.

Also, we may decide to move this logic to a turbosrc-service api call and handle the Octokit functionality there. We could remove the logic above and add an api call called checkScopes which queried Github utils in service via the GraphQL server.

**Comment by JeffreyLWood** [comment]
To ensure a user has admin/maintainer/push permissions to the current repo in addition to having the public_repo scope enabled we can see the permissions value in the response from Github which is console logged on the left:

### One of my repos which I have permissions for based on my token:
![Screen Shot 2022-09-19 at 10 42 08 AM](https://user-images.githubusercontent.com/75996017/191080205-1a99d357-638e-4804-aa0c-569f6d36bb17.png)

### Not a repo I have permissions for based on my token:
![Screen Shot 2022-09-19 at 10 41 07 AM](https://user-images.githubusercontent.com/75996017/191080295-8351f3cb-4464-4b5b-b3c7-eaa81dc4e8c0.png)

So the second screenshot should not render the Submit button, but rather a second warning saying something to the effect of "You do not have permissions to this repository". And possibly suggesting that they fork the repository instead or a field where they can enter a valid API key for that repository.

Would be interested to hear what you think.

**Comment by JeffreyLWood** [comment]
The most recent push to the branch scope has the following functionality:

- If a user tries to tokenize a repo for the first time, they are given a warning to update their permissions, which takes them through Github authentication with the proper scope added: public_repo. They can then tokenize one of their repositories.

- If a user completes the above step and is trying to tokenize a repo they do not have access to, they are prompted to enter a valid access token for the requested repository.

- If they copy and paste an access token which is valid for that repository, they can then tokenize the repo.
