### ISSUE TITLE
Fail to load a repo on switch to it from another

### ISSUE THREAD

**Issue by 7db9a** [turbo-src/extension#44]
After tokenizing repo A, navigating to repo B doesn't result in the extension recognizing repo B; it'll offer to tokenize repo B but with repo  A's name.

Furthermore, it appears the vote button believes the repo B pull request are repo A's, rendering fake conflicts.

**Comment by 7db9a** [comment]
Update: the vote may not be related to the above. And the mixed up names do eventually resolve itself. For some reason it may not do it on the first few refreshes of the web page

**Comment by JeffreyLWood** [comment]
URL changes seem to function well but not perfectly, changing tabs however is a serparate issue and will take time to troubleshoot. 

Working on branch fix-repoid-refresh for extension 

For starters I set function which gets the repoid and owner to set them as none and none if the URL is not github.com. 

Other than that I've tried a few things and will continue to try and get it to be as responsive as possible.
